trigger:
- master

pool:
  name: Azure Pipelines
  vmImage: 'ubuntu-latest'


steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install Python dependencies'


# Prepare Analysis Configuration task
- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'blacklock_sonar'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'Hq:sU0sxJI3h1BgU'

- script: |
    python manage.py test
  displayName: 'Run Django Tests'

# Run Code Analysis task
- task: SonarQubeAnalyze@5

# Publish Quality Gate Result task
- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'
